<?php
declare( strict_types=1 );

namespace Callismart\DBPrism\Query\Traits;

use Callismart\DBPrism\Utils\CaseExpression;

/**
 * Provides fluent structural routing for managing SQL HAVING aggregates.
 */
trait SupportsHavingTrait {
    use ColumnNormalizerTrait;
    /**
     * @var array $havings Internal structured tracking collection for aggregate expressions.
     */
    protected array $havings = [];

    /**
     * @var array $having_bindings Parameter parameters for the aggregate block.
     */
    protected array $having_bindings = [];

    /**
     * Intercept and register a standard aggregate condition filter.
     * * @param string $aggregate The function expression (e.g., 'COUNT(id)').
     * @param string $operator  Comparison operator.
     * @param mixed  $value     Scalar matching constraint.
     * @param string $boolean   Logical join state (AND / OR).
     * @return static Fluent builder instance.
     */
    public function having( string $aggregate, string $operator, mixed $value, string $boolean = 'AND' ) : static {
        // We initialize a dynamic proxy container that inherits QueryCriteriaTrait safely
        /** @var QueryCriteriaTrait $proxy */
        $proxy = new class { use QueryCriteriaTrait; };
        $proxy->where( $aggregate, $operator, $value, $boolean );

        // Extract the condition block descriptor maps generated by your trait logic
        foreach ( $proxy->get_conditions() as $condition ) {
            $this->havings[] = $condition;
        }

        // Push the scalar variable right into the dedicated having bindings array
        foreach ( $proxy->get_bindings() as $binding ) {
            $this->having_bindings[] = $binding;
        }

        return $this;
    }

    /**
     * Intercept and register an OR aggregate condition filter.
     */
    public function or_having( string $aggregate, string $operator, mixed $value ) : static {
        return $this->having( $aggregate, $operator, $value, 'OR' );
    }

    /**
     * Filter aggregate data using a dynamic conditional ANSI CASE evaluation statement.
     * * @param callable $callback Closure receiving an isolated CaseExpression instance.
     * @param string   $operator Comparison operator applied against the CASE block result.
     * @param mixed    $value    The target comparison value.
     * @param string   $boolean  Logical join state (AND / OR).
     * @return static Fluent builder instance.
     */
    public function having_case( callable $callback, string $operator, mixed $value, string $boolean = 'AND' ) : static {
        $case_expression = new CaseExpression();
        $callback( $case_expression );

        $this->havings[] = [
            'type'            => 'case_expression',
            'case_expression' => $case_expression,
            'operator'        => $operator,
            'value'           => $value,
            'boolean'         => $boolean
        ];

        // 1. Unpack inner parameters from CaseExpression branches chronologically
        foreach ( $case_expression->get_branches() as $branch ) {
            foreach ( $branch['criteria']->get_bindings() as $condition_binding ) {
                $this->having_bindings[] = $condition_binding;
            }

            $then_value = $branch['then_value'];
            if ( ! is_object( $then_value ) && ! ( is_string( $then_value ) && static::is_sql_expression( $then_value ) ) ) {
                $this->having_bindings[] = $then_value;
            }
        }

        $else_value = $case_expression->get_else();
        if ( null !== $else_value && ! is_object( $else_value ) && ! ( is_string( $else_value ) && static::is_sql_expression( $else_value ) ) ) {
            $this->having_bindings[] = $else_value;
        }

        // 2. Safely capture the comparison value parameter tracking bounds
        if ( ! is_object( $value ) && ! ( is_string( $value ) && static::is_sql_expression( $value ) ) ) {
            $this->having_bindings[] = $value;
        }

        return $this;
    }

    /**
     * Retrieve all structured aggregate constraints.
     */
    public function get_havings() : array {
        return $this->havings;
    }

    /**
     * Retrieve aggregate query parameters.
     */
    public function get_having_bindings() : array {
        return $this->having_bindings;
    }
}